# Generated by Django 5.0.9 on 2024-10-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeimages', '0003_recipeimage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='tag',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
