# Generated by Django 5.0.9 on 2024-10-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeimages', '0004_recipeimage_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
