# Generated by Django 5.0.9 on 2024-10-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeimages', '0005_tag_alter_recipeimage_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
