# Generated by Django 5.0.9 on 2024-10-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeimages', '0006_alter_recipeimage_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='tag',
        ),
    ]
