# Generated by Django 5.0.9 on 2024-12-08 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_alter_portfoliocontent_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocontent',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
