# Generated by Django 5.0.9 on 2024-12-08 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_remove_portfoliocontent_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='course_portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
