# Generated by Django 5.0.9 on 2024-11-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
