# Generated by Django 5.0.9 on 2024-12-04 04:23

import courses.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', courses.fields.OrderField(blank=True)),
                ('date', models.DateField()),
                ('link', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
