# Generated by Django 5.0.9 on 2024-12-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_portfolio_instructors_portfolio_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='overview',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
