# Generated by Django 5.0.9 on 2024-12-06 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_portfolio_link_portfolio_overview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='instructors',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='portfolios_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
