# Generated by Django 5.0.9 on 2024-12-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_portfoliofile_portfolioimage_portfoliotext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliofile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='portfoliotext',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='portfoliovideo',
            name='owner',
        ),
        migrations.DeleteModel(
            name='PortfolioContent',
        ),
        migrations.DeleteModel(
            name='PortfolioFile',
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
        migrations.DeleteModel(
            name='PortfolioText',
        ),
        migrations.DeleteModel(
            name='PortfolioVideo',
        ),
    ]
